// Service worker: makes NoPaste work offline and load instantly after the first visit.
// VERSION and PRECACHE_URLS are generated by tools/build.mjs - run it after changing any served file.

// build:start
const VERSION = 'c4db0657104f';
const PRECACHE_URLS = [
    '/',
    'script.js',
    'style.css',
    'deps.js',
    'deps.css',
    'editor/editor.js',
    'editor/chunks/chunk-7YKLX2SU.js',
    'vendor/lzma/lzma_worker.min.js',
    'vendor/fonts/JetBrainsMono-Regular.woff2',
    'vendor/fonts/roboto-latin-400-normal.woff2',
];
// build:end

const PRECACHE = 'precache-' + VERSION;
const LANGUAGES = 'languages-' + VERSION;

// Language chunks are only downloaded when a language is selected; they are cached the first time they are used.
const LANGUAGE_REGEXP = /\/editor\/chunks\//;

// The install handler takes care of precaching the resources we always need.
// `cache: 'reload'` bypasses the HTTP cache so a new version never precaches stale files.
self.addEventListener('install', (event) => {
    event.waitUntil(
        caches
            .open(PRECACHE)
            .then((cache) => cache.addAll(PRECACHE_URLS.map((url) => new Request(url, { cache: 'reload' }))))
            .then(() => self.skipWaiting())
    );
});

// The activate handler takes care of cleaning up old caches.
self.addEventListener('activate', (event) => {
    const currentCaches = [PRECACHE, LANGUAGES];
    event.waitUntil(
        caches
            .keys()
            .then((cacheNames) => cacheNames.filter((cacheName) => !currentCaches.includes(cacheName)))
            .then((cachesToDelete) => Promise.all(cachesToDelete.map((cacheToDelete) => caches.delete(cacheToDelete))))
            .then(() => self.clients.claim())
    );
});

// The fetch handler serves responses from a cache.
// If no response is found, language chunks are fetched and put in the runtime cache; anything else is just fetched.
self.addEventListener('fetch', (event) => {
    if (event.request.method !== 'GET' || !event.request.url.startsWith(self.location.origin)) {
        return;
    }
    event.respondWith(
        caches.match(event.request, { ignoreSearch: true }).then((cachedResponse) => {
            if (cachedResponse) {
                return cachedResponse;
            }

            if (!LANGUAGE_REGEXP.test(new URL(event.request.url).pathname)) {
                return fetch(event.request);
            }

            return caches.open(LANGUAGES).then((cache) =>
                fetch(event.request).then((response) => {
                    if (!response.ok) {
                        return response;
                    }
                    // Put a copy of the response in the runtime cache.
                    return cache.put(event.request, response.clone()).then(() => response);
                })
            );
        })
    );
});
